#!/bin/bash

if [ $1 == "update" ]
then
  echo ">> updating repo 'lfs' ... " -n
  curl -o /usr/share/shpkg/packages.list https://raw.githubusercontent.com/cmcheeseman/shlfs/main/repo/packages.list
fi

if [ $1 == "install" ]
then
  if [ -z $(cat /usr/share/shpkg/packages.list | grep $2) ]
  then
    echo package $2 doesnt exist
    exit
  fi
  echo ">> downloading package $2 ..."
  wget -O /usr/share/shpkg/build/$2.tar.gz https://github.com/cmcheeseman/shlfs/raw/main/repo/$2.tar.gz
  tar -xvf /usr/share/shpkg/build/$2.tar.gz -C /usr/share/shpkg/build/
  cd /usr/share/shpkg/build/$2
  bash install
  echo ">> cleaning up ..."
  rm -rvf /usr/share/shpkg/build/$2*
  echo -n
  echo "done!"
fi
